/**
 * Inspect — and, with `--purge`, clear — stored job history.
 *
 * Usage:
 *   npx tsx src/scripts/jobHistory.ts            count only, changes nothing
 *   npx tsx src/scripts/jobHistory.ts --purge    delete every stored job
 *
 * WHAT --purge DELETES
 *
 *   processing_jobs      every job, and by `on delete cascade` its
 *   processed_products   ready-to-order rows and
 *   attention_products   needs-attention rows
 *   job_row_overrides    per-line admin decisions, which belong to a job
 *
 * WHAT IT DELIBERATELY KEEPS
 *
 *   product_overrides    "this description means THIS product"
 *
 * That table is not job history. It is the accumulated result of every manual
 * correction an admin has ever made, keyed on the description rather than on
 * any job, and it is what stops the same product being corrected every Monday.
 * Deleting it because it sits nearby would throw away the one thing in this
 * schema that cannot be regenerated by re-uploading a file.
 *
 * Counting first and deleting second is not ceremony: the count is the only
 * record of what was there once the delete has run.
 */

import 'dotenv/config';
import { getSupabaseClient } from '../db/supabase.js';

const TABLES = [
  'processing_jobs',
  'processed_products',
  'attention_products',
  'job_row_overrides',
  'product_overrides',
] as const;

const db = getSupabaseClient();

async function countRows(table: string): Promise<number | null> {
  const { count, error } = await db.from(table).select('*', { count: 'exact', head: true });
  if (error) {
    console.log(`  ${table.padEnd(22)} ERROR: ${error.message}`);
    return null;
  }
  return count ?? 0;
}

console.log('\nStored job history\n');
const before: Record<string, number | null> = {};
for (const table of TABLES) {
  before[table] = await countRows(table);
  if (before[table] !== null) {
    const keeps = table === 'product_overrides' ? '   (kept by --purge)' : '';
    console.log(`  ${table.padEnd(22)} ${String(before[table]).padStart(7)} row(s)${keeps}`);
  }
}

if (!process.argv.includes('--purge')) {
  console.log('\nNothing changed. Pass --purge to delete.\n');
  process.exit(0);
}

console.log('\nPurging...\n');

// Children first, then the parent. The cascade would handle the children on its
// own, but deleting them explicitly means a partial failure is visible in the
// counts below rather than silently leaving orphans if the cascade is ever
// dropped from the schema.
for (const table of ['processed_products', 'attention_products', 'job_row_overrides']) {
  const { error } = await db.from(table).delete().not('job_id', 'is', null);
  console.log(`  ${table.padEnd(22)} ${error ? `ERROR: ${error.message}` : 'cleared'}`);
}

const { error: jobsError } = await db
  .from('processing_jobs')
  .delete()
  .not('job_id', 'is', null);
console.log(`  ${'processing_jobs'.padEnd(22)} ${jobsError ? `ERROR: ${jobsError.message}` : 'cleared'}`);

console.log('\nAfter\n');
for (const table of TABLES) {
  const count = await countRows(table);
  if (count !== null) console.log(`  ${table.padEnd(22)} ${String(count).padStart(7)} row(s)`);
}
console.log('');
